version: 2.1

executors:
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:latest  # Use the Playwright Docker image
    working_directory: ~/repo

jobs:
  build:
    executor: playwright-executor
    steps:
      - checkout  # Checkout the code
      - run:
          name: Install dependencies
          command: |
            npm ci  # Install dependencies using npm ci (clean install)
            npx playwright install  # Install Playwright browsers
      - run:
          name: Run Playwright tests
          command: |
            npx playwright test  # Run tests with reporters
            # npx playwright show-report  # Show the test report
      - store_test_results:
          path: results.xml  # Save test results
      - store_artifacts:
          path: playwright-report  # Save the Playwright report

workflows:
  version: 2
  test:
    jobs:
      - build  # Execute the build job
